version: '3.7'

services:
  e2e_playwright:
    build:
      context: .
      dockerfile: packages/e2e-tests/Dockerfile
      args:
        gid: ${GID}
        uid: ${UID}
    environment:
      - NODE_ENV=test
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - DC_ACCOUNTS_DIR=../../e2e-tests/data/accounts
    volumes:
      - ./:/app
    container_name: dc-desktop-e2e-tests
    entrypoint: ['/bin/sh', '-c']
    user: ${UID}:${GID}
    ports:
      - 3000:3000
    command:
      - |
        pnpm install
        pnpm run e2e --project Chrome
        
